web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./code:/code
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
        - ./nginx/amplify.conf:/etc/nginx/conf.d/amplify.conf
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ./code:/code