version: "2"

services:
    web:
        image: nginx:latest
        restart: always
        volumes:
            # - ./code:/var/www/html
            - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            #- ./conf/nginx/site.conf:/etc/nginx/conf.d/default.conf
            - ./conf/nginx/drupal.conf:/etc/nginx/conf.d/default.conf
            - ./conf/nginx/amplify.conf:/etc/nginx/conf.d/amplify.conf
        volumes_from:
          - storage-drupal
        links:
            - php
        #work with jwilder/nginx-proxy
        ports:
            - "8080:80"
        environment:
          - VIRTUAL_HOST=yourapp.yourdomain.com
    # php:
    #     image: php:7-fpm
    #     volumes:
    #         - ./code:/var/www/html
    #         - ./conf/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    
    #api-code-app > drupal:fpm > php:7-fpm 只执行一次！！！
    php:
        # build: ./src/api
        image: drupal:fpm
        image: drupal-fpm-for-api #给build镜像后的image命名
        restart: always
        links:
          - "db"
        volumes_from:
          - storage-drupal
        volumes:
          # - ./code:/code
          - ./conf/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf


    db:
      image: mysql:latest
      # container_name: mysql #Specify a custom container name, rather than a generated default name.
      hostname: dbhost
      restart: always
      volumes_from:
        - storage-mysql
      # volumes:
      #  - /var/lib/mysql
      environment:
        - MYSQL_USER=drupal
        - MYSQL_PASSWORD=drupal
        - MYSQL_DATABASE=drupal
        - MYSQL_ROOT_PASSWORD=drupal

    #################
    storage-drupal:
      image: drupal:fpm
      # container_name: storagedrupal
      command: ["chmod","-R","777","/var/www/html/sites/default/files"] #v3# create_only: true
      volumes:
        - /var/www/html/sites/default
        - /var/www/html/sites/default/files
      volumes_from:
        - storage-drupal-code
    #################    
    storage-mysql:
      image: mysql:latest
      command: ["echo","create_only"] #v3# create_only: true
      volumes:
          - /var/lib/mysql
    #################
    ###################################################
    # update frequestly , when commit code to git  need rebuild it
    ###################################################
    storage-drupal-code:
      image: drupal:fpm
      command: ["echo","create_only"]
      volumes:
        - /var/www/html/
        # TODO: Some common subdirectories include "contrib" for
        # contributed modules, and "custom" for custom modules.
        # - /var/www/html/modules/custom
        # - /var/www/html/themes/custom
    #################